name: fusion_app_store
description: "Publish Once, to any platform."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  flutter_clean_architecture: ^5.0.4
  responsive_framework: ^1.1.1
  gap: ^3.0.1
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  flutter_animate: ^4.3.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  animated_background: ^2.0.0
  aurora: ^1.0.0
  metaballs: ^1.5.0
  bcrypt: ^1.1.3
  drift: ^2.14.1
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.1
  path: ^1.8.3
  syncfusion_flutter_charts: ^24.1.43+1
  file_picker: ^6.1.1
  drift_db_viewer: ^2.0.0
  palette_generator: ^0.3.3+3
  firebase_storage: ^11.6.5
  http: ^1.2.0
  uuid: ^4.3.3
  intl: ^0.19.0
  url_launcher: ^6.2.5
  flutter_osm_plugin: ^0.70.4
  geocode: ^1.0.3
  url_strategy: ^0.2.0
  razorpay_web: ^1.4.2
  fl_chart: ^0.67.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  drift_dev: ^2.14.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/animations/
    - assets/icons/
    - assets/icons/platforms/
    - assets/icons/home/
    - assets/icons/companies/
    - assets/icons/onboarding/
    - assets/icons/reactions/
    - assets/icons/esrb/
    - assets/artworks/
    - assets/illustrations/
    - assets/avatars/
  fonts:
    - family: Sen
      fonts:
        - asset: fonts/Sen/Sen-Regular.ttf
          weight: 400
        - asset: fonts/Sen/Sen-Medium.ttf
          weight: 500
        - asset: fonts/Sen/Sen-Bold.ttf
          weight: 700
    - family: Satoshi
      fonts:
        - asset: fonts/Satoshi/Satoshi-Regular.otf
          weight: 400
        - asset: fonts/Satoshi/Satoshi-Medium.otf
          weight: 500
        - asset: fonts/Satoshi/Satoshi-Bold.otf
          weight: 700
